workflows:
  meals-workflows: # workflow ID
    name: Meals Pipeline
    environment:
      ios_signing:
        bundle_identifier: mfa.app
    scripts:
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - mfahmiardiyannto@gmail.com # Isikan email untuk notifikasi status building.
