workflows:
  meals-project-debug: # workflow ID
    name: Meals Pipeline
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "ios-theMealsApp.xcworkspace" # Isikan nama project Anda.
          XCODE_SCHEME: "ios-theMealsApp" # Isikan nama scheme project Anda.
    scripts:
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - mfahmiardiyannto@gmail.com # Isikan email untuk notifikasi status building.
